
Конструкция Try catch finally расширяет [[Try catch|try-catch]], добавляя блок [[Константы|finally]]. Этот блок выполняется всегда, независимо от того, возникло исключение или нет. Он часто используется для выполнения завершающих действий, таких как освобождение ресурсов (*например, закрытие файлов или сетевых соединений*).

**Пример:**
![[Pasted image 20250322220851.png]]
**Вывод:**
![[Pasted image 20250322220909.png]]
- В блоке **try** мы пытаемся открыть файл **file.txt** и прочитать из него первую строку.
- Если файл не существует, возникает исключение **IOException**, и управление переходит в блок **catch**, где выводится сообщение об ошибке.
- Блок **finally** выполняется независимо от результата: он проверяет, был ли открыт файл (*т.е. не равен ли reader null*), и если да, закрывает его. В данном случае файл не был открыт, поэтому закрытие не происходит, но сообщение всё равно выводится.